###
# Image Processing
###

deploy-image_processing:
  variables:
    SERVICE_NAME: image_processing
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA~g" ./$SERVICE_NAME/kubernetes/deployment.yml 
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/service.yml -n project-dev
  only:
    refs:
      - dev
    changes:
      - image_processing/**/*
