###
# Image Processing
###

test-image_processing:
  image: python:3.9
  stage: test
  before_script:
    - pip3 install -r engine/requirements.txt
    - pip3 install pytest pytest-asyncio aiofile
  script:
    - cd engine
    - python3 -m pytest --asyncio-mode=auto
  only:
    ref:
      - dev
    changes:
      - image_processing/**/*


build-image_processing:
  variables:
    SERVICE_NAME: image_processing
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
    - docker pull $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest || true
    - docker build --network host -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest -f ./$SERVICE_NAME/dockerfile ./$SERVICE_NAME
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest
  only:
    refs:
      - dev
    changes:
      - image_processing/**/*
  
deploy-image_processing:
  variables:
    SERVICE_NAME: image_processing
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA~g" ./$SERVICE_NAME/kubernetes/deployment.yml 
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/service.yml -n project-dev
  only:
    refs:
      - dev
    changes:
      - image_processing/**/*
