apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        #image: registry.forge.hefr.ch/mse_pi/services/mongo:latest
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
      imagePullSecrets:
      - name: mysecretdeployer
