version: '3.7'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/workspaces/csia-pme
    command: poetry run mkdocs serve --dev-addr 0.0.0.0:8000
