###
# Digit recognition
###

include:
  - digit_recognition/model.yml

download-model:
  variables:
    S3_URL: https://minio1.isc.heia-fr.ch:9007
    S3_KEY_ID: $MINIO_ACCESS_KEY
    S3_SECRET_KEY: $MINIO_SECRET_KEY
  image: python:3.9
  stage: prepare
  before_script:
    - pip3 install -r utils/requirements.txt
  script:
    - python3 utils/s3client.py pull model.h5 $DIGIT_RECOGNITION_S3_MODEL_PATH
  artifacts:
    paths:
    - model.h5
    expire_in: 10 min
  only:
    refs:
      - merge_requests
      - dev
    changes:
      - digit_recognition/**/*

test-digit_recognition:
  image: $CI_REGISTRY_IMAGE/basic_image:latest
  stage: test
  before_script:
    - pip3 install -r digit_recognition/requirements.txt
    - pip3 install pytest pytest-asyncio aiofile
  script:
    - cp model.h5 digit_recognition
    - cd digit_recognition
    - python3 -m pytest --asyncio-mode=auto
    - rm model.h5
  only:
    refs:
      - merge_requests
    changes:
      - digit_recognition/**/*

deploy-digit_recognition:
  variables:
    SERVICE_NAME: digit_recognition
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA~g" ./$SERVICE_NAME/kubernetes/deployment.yml 
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/service.yml -n project-dev
  only:
    refs:
      - dev
    changes:
      - digit_recognition/**/*
