###
# Digit recognition
###

include:
  - digit_recognition/model.yml

download-model:
  variables:
    S3_URL: https://minio1.isc.heia-fr.ch:9007
    S3_KEY_ID: $MINIO_ACCESS_KEY
    S3_SECRET_KEY: $MINIO_SECRET_KEY
  image: python:3.9
  stage: prepare
  before_script:
    - pip3 install -r utils/requirements.txt
  script:
    - python3 utils/s3client.py pull model.h5 $DIGIT_RECOGNITION_S3_MODEL_PATH
  artifacts:
    paths:
    - model.h5
    expire_in: 10 min
  only:
    refs:
      - merge_requests
      - dev
    changes:
      - digit_recognition/**/*

test-digit_recognition:
  image: python:3.9
  stage: test
  before_script:
    - apt-get update -y && apt-get install ffmpeg libsm6 libxext6 -y
    - pip3 install -r digit_recognition/requirements.txt
    - pip3 install pytest pytest-asyncio aiofile
  script:
    - cp model.h5 digit_recognition
    - cd digit_recognition
    - python3 -m pytest --asyncio-mode=auto
    - rm model.h5
  only:
    refs:
      - merge_requests
    changes:
      - digit_recognition/**/*

build-digit_recognition:
  variables:
    SERVICE_NAME: digit_recognition
    IMAGE_TAG_LAST: $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
    - mv model.h5 $SERVICE_NAME
    - docker pull $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest || true
    - docker build --network host --cache-from $IMAGE_TAG_LAST -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest -f ./$SERVICE_NAME/dockerfile ./$SERVICE_NAME
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest
  only:
    refs:
      - dev
    changes:
      - digit_recognition/**/*
  dependencies:
    - download-model
  
deploy-digit_recognition:
  variables:
    SERVICE_NAME: digit_recognition
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA~g" ./$SERVICE_NAME/kubernetes/deployment.yml 
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/service.yml -n project-dev
  only:
    refs:
      - dev
    changes:
      - digit_recognition/**/*
