apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        #image: registry.forge.hefr.ch/mse_pi/services/engine:latest
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: "80"
        - name: APP_LOG
          value: info
        - name: APP_ENGINE
          value: "http://service-engine.project-dev.svc.cluster.local"
        - name: APP_EXTERNAL_URL
          value: "https://pi-engine.kube.isc.heia-fr.ch"
        - name: S3_URL
          value: "https://minio1.isc.heia-fr.ch:9007"
        - name: S3_KEY_ID
          value: S3_KEY_ID_PLACEHOLDER
        - name: S3_SECRET_KEY
          value: S3_SECRET_KEY_PLACEHOLDER
        - name: S3_BUCKET
          value: "mse-pi"
        - name: REG_STORAGE_TYPE
          value: "S3"
      imagePullSecrets:
      - name: mysecretdeployer
