apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: engine
