apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
  labels:
    app: engine
data:
  HOST: http://localhost:8080
  ENVIRONMENT: development
  LOG_LEVEL: debug
  DATABASE_URL: sqlite:///engine.db
  DATABASE_CONNECT_ARGS: "{ \"check_same_thread\": \"False\" }"
  S3_ACCESS_KEY_ID: minio
  S3_SECRET_ACCESS_KEY: minio123
  S3_REGION: eu-central-2
  S3_HOST: http://localhost:9000
  S3_BUCKET: engine
