apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
  labels:
    app: engine
data:
  APP_EXTERNAL_URL: http://engine-service:8080
  S3_URL: http://minio-service:9000
  S3_KEY_ID: minio
  S3_SECRET_KEY: minio123
  S3_BUCKET: csia-pme
  MONGO_URI: mongodb://mongo:secret@mongo-service:27017
  MONGO_DB: csia-pme
