apiVersion: v1
kind: ConfigMap
metadata:
  name: stat-anno-detection-config
  labels:
    app: stat-anno-detection
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URL: http://engine-service:8000
  SERVICE_URL: http://stat-anno-detection-service:8787
