###
# Engine
###

test-engine:
  image: $CI_REGISTRY_IMAGE/basic_image:latest
  stage: test
  before_script:
    - pip3 install -r engine/requirements.txt
    - pip3 install pytest pytest-asyncio aiofile
  script:
    - cd engine
    - python3 -m pytest --asyncio-mode=auto
  only:
    refs:
      - merge_requests
    changes:
      - engine/**/*

deploy-engine:
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/engine:$CI_COMMIT_SHORT_SHA~g" ./engine/kubernetes/deployment.yml 
    - sed -i "s~S3_KEY_ID_PLACEHOLDER~$MINIO_ACCESS_KEY~g" ./engine/kubernetes/deployment.yml
    - sed -i "s~S3_SECRET_KEY_PLACEHOLDER~$MINIO_SECRET_KEY~g" ./engine/kubernetes/deployment.yml
    - sed -i "s~MONGO_URI_PLACEHOLDER~$MONGO_URI~g" ./engine/kubernetes/deployment.yml
    - kubectl apply -f ./engine/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./engine/kubernetes/service.yml -n project-dev
    # Create Ingress
    - kubectl -n project-dev apply -f ./engine/kubernetes/ingress.yml
  only:
    refs:
      - dev
    changes:
      - engine/**/*
