# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: deploy_app_on_rancher_kubernetes_cluster
description: Deploy app on a Rancher Kubernetes cluster

inputs:
  kubectl-binary-url:
    description: kubectl binary URL
    required: true
    default: https://dl.k8s.io/release/v1.25.3/bin/linux/amd64/kubectl
  kubectl-binary-sha-url:
    description: kubectl binary SHA URL
    required: true
    default: https://dl.k8s.io/v1.25.3/bin/linux/amd64/kubectl.sha256
  kubectl-args:
    description: kubectl arguments
    required: true
  rancher-cli-archive-url:
    description: Rancher CLI archive URL
    required: true
    default: https://github.com/rancher/cli/releases/download/v2.6.9/rancher-linux-amd64-v2.6.9.tar.gz
  rancher-cli-archive-sha-url:
    description: Rancher CLI archive SHA URL
    required: true
    default: https://github.com/rancher/cli/releases/download/v2.6.9/sha256sum.txt
  rancher-api-endpoint-url:
    description: Rancher API endpoint URL
    required: true
  rancher-bearer-token:
    description: Rancher Bearer token
    required: true

runs:
  using: composite
  steps:
    - name: Get filenames from URLs
      shell: bash
      run: |
        echo "KUBECTL_BINARY_NAME=$(basename "${{ inputs.kubectl-binary-url }}")" >> $GITHUB_ENV
        echo "KUBECTL_BINARY_SHA_NAME=$(basename "${{ inputs.kubectl-binary-sha-url }}")" >> $GITHUB_ENV
        echo "RANCHER_CLI_ARCHIVE_NAME=$(basename "${{ inputs.rancher-cli-archive-url }}")" >> $GITHUB_ENV
        echo "RANCHER_CLI_ARCHIVE_SHA_NAME=$(basename "${{ inputs.rancher-cli-archive-sha-url }}")" >> $GITHUB_ENV

    - name: Download kubectl binary
      shell: bash
      run: curl -LO -s "${{ inputs.kubectl-binary-url }}"

    - name: Download kubectl binary SHA
      shell: bash
      run: curl -LO -s "${{ inputs.kubectl-binary-sha-url }}"

    - name: Verify kubectl binary with SHA checksum
      shell: bash
      run: echo "$(cat $KUBECTL_BINARY_SHA_NAME) kubectl" | sha256sum --check

    - name: Install kubectl binary
      shell: bash
      run: sudo install -o root -g root -m 0755 $KUBECTL_BINARY_NAME /usr/local/bin/kubectl

    - name: Download Rancher CLI archive
      shell: bash
      run: curl -LO -s "${{ inputs.rancher-cli-archive-url }}"

    - name: Download Rancher CLI archive SHA
      shell: bash
      run: curl -LO -s "${{ inputs.rancher-cli-archive-sha-url }}"

    - name: Verify Rancher CLI archive with SHA checksum
      shell: bash
      run: sha256sum --check --ignore-missing $RANCHER_CLI_ARCHIVE_SHA_NAME

    - name: Decompress Rancher CLI archive
      shell: bash
      run: tar -xzf $RANCHER_CLI_ARCHIVE_NAME

    - name: Install Rancher CLI binary
      shell: bash
      run: sudo install -o root -g root -m 0755 rancher-*/rancher /usr/local/bin/rancher

    - name: Login to the Rancher server
      shell: bash
      run: rancher login ${{ inputs.rancher-api-endpoint-url }} --token ${{ inputs.rancher-bearer-token }}

    - name: Execute kubectl command
      shell: bash
      run: rancher kubectl ${{ inputs.kubectl-args }}
