apiVersion: apps/v1
kind: Deployment
metadata:
  name: average-shade
  labels:
    app: average-shade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: average-shade
  template:
    metadata:
      labels:
        app: average-shade
    spec:
      containers:
      - name: average-shade
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: "80"
        - name: APP_LOG
          value: info
        - name: APP_ENGINE
          value: "http://engine-service.project-dev.svc.cluster.local"
        - name: APP_SERVICE
          value: "http://average-shade-service.project-dev.svc.cluster.local"
      imagePullSecrets:
      - name: mysecretdeployer
