apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the stateful set
  name: average-shade-stateful
  labels:
    app: average-shade
spec:
  serviceName: average-shade
  replicas: 1
  selector:
    matchLabels:
      app: average-shade
  template:
    metadata:
      labels:
        app: average-shade
    spec:
      containers:
      - name: average-shade
        image: ghcr.io/csia-pme/csia-pme-average-shade:latest
        # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: "80"
        - name: APP_LOG
          value: info
        envFrom:
          - configMapRef:
              name: average-shade-config
