apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the pod
  name: average-shade-pod
  labels:
    app: average-shade
spec:
  containers:
  - name: average-shade
    image: csia-pme/average-shade
    # As we use the local image, there is no need to pull the image
    imagePullPolicy: Never
    ports:
    - name: http
      containerPort: 80 
    env:
    - name: APP_HOST
      value: 0.0.0.0
    - name: APP_PORT
      value: "80"
    - name: APP_LOG
      value: info
    - name: APP_ENGINE
      value: "http://engine-service:8080"
    - name: APP_SERVICE
      value: "http://average-shade-service:8282"
    - name: APP_NOTIFY_CRON
      value: "30"
