apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the stateful set
  name: digit-recognition-stateful
  labels:
    app: digit-recognition
spec:
  serviceName: digit-recognition
  replicas: 1
  selector:
    matchLabels:
      app: digit-recognition
  template:
    metadata:
      labels:
        app: digit-recognition
    spec:
      containers:
      - name: digit-recognition
        image: ghcr.io/csia-pme/csia-pme-digit-recognition:latest
        # If you build the image locally, change the next line to `imagePullPolicy: Never` - there is no need to pull the image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: "80"
        - name: APP_LOG
          value: info
        envFrom:
          - configMapRef:
              name: digit-recognition-config
