apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "80"
          # This env variable doesn't work in production because JavaScript is awesome !!!
          # It is now an arg of the docker build. Set it up in the gitlab-ci
        - name: REACT_APP_ENGINE_URL
          value: "https://pi-engine.kube.isc.heia-fr.ch"

      imagePullSecrets:
      - name: mysecretdeployer
