###
# Average Shade
###

test-average_shade:
  image: $CI_REGISTRY_IMAGE/basic_image:latest
  stage: test
  before_script:
    - pip3 install -r average_shade/requirements.txt
    - pip3 install pytest pytest-asyncio aiofile
  script:
    - cd average_shade
    - python3 -m pytest --asyncio-mode=auto
  only:
    refs:
      - merge_requests
    changes:
      - average_shade/**/*

build-average_shade:
  variables:
    SERVICE_NAME: average_shade
    IMAGE_TAG_LAST: $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
    - docker pull $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest || true
    - docker build --network host --cache-from $IMAGE_TAG_LAST -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest -f ./$SERVICE_NAME/dockerfile ./$SERVICE_NAME
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$SERVICE_NAME:latest
  only:
    refs:
      - dev
    changes:
      - average_shade/**/*
  
deploy-average_shade:
  variables:
    SERVICE_NAME: average_shade
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  tags:
    - k8s
  # when: manual
  script:
    - echo $KUBE_CONFIG | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    # Check if KUBECONFIG is configured
    - kubectl config get-contexts
    # Change name of 
    - sed -i "s~IMAGE_NAME~$CI_REGISTRY_IMAGE/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA~g" ./$SERVICE_NAME/kubernetes/deployment.yml 
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/deployment.yml -n project-dev
    # Create services
    - kubectl apply -f ./$SERVICE_NAME/kubernetes/service.yml -n project-dev
  only:
    refs:
      - dev
    changes:
      - average_shade/**/*
