apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-analyzer
  labels:
    app: face-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-analyzer
  template:
    metadata:
      labels:
        app: face-analyzer
    spec:
      containers:
      - name: face-analyzer
        image: IMAGE_NAME
        #image: registry.forge.hefr.ch/mse_pi/services/face_analyzer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: "80"
        - name: APP_LOG
          value: info
        - name: APP_ENGINE
          value: "http://service-engine.project-dev.svc.cluster.local"
        - name: APP_SERVICE
          value: "http://service-face-analyzer.project-dev.svc.cluster.local"
      imagePullSecrets:
      - name: mysecretdeployer
