apiVersion: v1
kind: ConfigMap
metadata:
  name: face-analyzer-config
  labels:
    app: face-analyzer
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URL: http://engine-service:8000
  SERVICE_URL: http://face-analyzer-service:8484
