apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8585
      targetPort: 80
      protocol: TCP
  selector:
    app: face-detection
