apiVersion: v1
kind: ConfigMap
metadata:
  name: face-detection-config
  labels:
    app: face-detection
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URL: http://engine-service:8000
  SERVICE_URL: http://face-detection-service:8282
