apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the pod
  name: face-detection-pod
  labels:
    app: face-detection
spec:
  containers:
  - name: face-detection
    image: csia-pme/face-detection
    # As we use the local image, there is no need to pull the image
    imagePullPolicy: Never
    ports:
    - name: http
      containerPort: 80 
    env:
    - name: APP_HOST
      value: 0.0.0.0
    - name: APP_PORT
      value: "80"
    - name: APP_LOG
      value: info
    - name: APP_ENGINE
      value: "http://engine-service:8080"
    - name: APP_SERVICE
      value: "http://face-detection-service:8585"
    - name: APP_NOTIFY_CRON
      value: "30"
