# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: average_shade_workflow
run-name: average_shade workflow

on:
  push:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/average-shade.yml
      - average_shade/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check modified paths/files
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            build-and-push-docker-image-to-github-action:
              - '.github/actions/build-and-push-docker-image-to-github/action.yml'
            test-python-app-action:
              - '.github/actions/test-python-app/action.yml'
            average-shade-workflow:
              - '.github/workflows/average-shade.yml'
            average-shade:
              - './average_shade/**/*'

      # Only run if the action or workflow have been changed or if the Python app has been changed
      - if: steps.changes.outputs.test-python-app-action == 'true' || steps.changes.outputs.average-shade-workflow == 'true' || steps.changes.outputs.average-shade == 'true'
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./average_shade

      # Only run on main and if the action or workflow have been changed or if the Python app has been changed
      - if: github.ref == 'refs/heads/main' && (steps.changes.outputs.build-and-push-docker-image-to-github-action == 'true' || steps.changes.outputs.average-shade-workflow == 'true' || steps.changes.outputs.average-shade == 'true')
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-average-shade
          docker-image-context: ./average_shade
