# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: digit_recognition_workflow
run-name: digit_recognition workflow

on:
  push:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/run-ml-experiment-with-dvc/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/digit-recognition.yml
      - digit_recognition/model_creation/**/*
      - digit_recognition/model_serving/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/run-ml-experiment-with-dvc
        with:
          ml-experiment-path: ./digit_recognition/model_creation
          aws-access-key-id: ${{ secrets.DIGIT_RECOGNITION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DIGIT_RECOGNITION_AWS_SECRET_ACCESS_KEY }}

      # Move the model to model_serving directory
      - shell: bash
        run: mv ./digit_recognition/{model_creation,model_serving}/mnist_model.h5

      - uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./digit_recognition/model_serving

      # Only run on main
      - if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-digit-recognition
          docker-image-context: ./digit_recognition/model_serving
