# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: engine_workflow
run-name: engine workflow

on:
  push:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/engine.yml
      - engine/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    services:
      # https://stackoverflow.com/questions/60849745/how-can-i-run-a-command-in-github-action-service-containers
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        ports:
          - 9000:9000
        options: --name=minio

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: ./engine

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./engine

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-engine
          docker-image-context: ./engine

      - name: Prepare configuration files with secrets from GitHub Secrets
        # Only run on main
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: engine/kubernetes
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.ENGINE_S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.ENGINE_S3_SECRET_ACCESS_KEY }}
          S3_HOST: ${{ secrets.ENGINE_S3_HOST }}
        run: |
          echo "${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}"
          # Set Engine configuration
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' engine.config-map.yml | envsubst > new-engine.config-map.yml && mv new-engine.config-map.yml engine.config-map.yml

      - name: Deploy Engine on Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./engine/kubernetes
          kubectl-args: |
            apply \
              -f engine.config-map.yml \
              -f engine.stateful.yml \
              -f engine.service.yml \
              -f engine.ingress.yml
