# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: face_detection_workflow
run-name: face_detection workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/face-detection.yml
      - ./face_detection/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-face-detection
          docker-image-context: ./face_detection
