# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: face_analyzer_workflow
run-name: face_analyzer workflow

on:
  push:
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/actions/execute-command-on-kubernetes-cluster/action.yml
      - .github/actions/test-python-app/action.yml
      - .github/workflows/face-analyzer.yml
      - services/face_analyzer/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: ./services/face_analyzer

      - name: Build and push Docker image to GitHub
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-face-analyzer
          docker-image-context: ./services/face_analyzer

      - name: Prepare configuration files with secrets from GitHub Secrets
        # Only run on main
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: services/face_analyzer/kubernetes
        env:
          APP_ENGINE: https://engine-csia-pme.kube.isc.heia-fr.ch
          APP_SERVICE: https://face-analyzer-csia-pme.kube.isc.heia-fr.ch
        run: |
          # Set face_analyzer configuration
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' face-analyzer.config-map.yml | envsubst > new-face-analyzer.config-map.yml && mv new-face-analyzer.config-map.yml face-analyzer.config-map.yml

      - name: Deploy face_analyzer on Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./services/face_analyzer/kubernetes
          kubectl-args: |
            apply \
              -f face-analyzer.config-map.yml \
              -f face-analyzer.stateful.yml \
              -f face-analyzer.service.yml \
              -f face-analyzer.ingress.yml
