# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: webapp_workflow
run-name: webapp workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/workflows/webapp.yml
      - webapp/**/*

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: webapp
        run: npm ci --legacy-peer-deps

      - name: Build app
        working-directory: webapp
        env:
          REACT_APP_ENGINE_URL: https://engine-csia-pme.kube.isc.heia-fr.ch
          # So it does not treat warnings as errors
          CI: false
        run: npm run build

      - name: Build and push Docker image to GitHub
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-webapp
          docker-image-context: ./webapp

      - name: Deploy Webapp on Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: csia-pme-prod
          kubectl-context: ./webapp/kubernetes
          kubectl-args: |
            apply \
              -f webapp.stateful.yml \
              -f webapp.service.yml \
              -f webapp.ingress.yml
